///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/song.aks
/// Generation time: ma., 31 de oct. de 2017 19:45:48
///

/// Song 'song_ingame' metadata macros
#define song_ingame_address  0x4000
#define song_ingame_size     2794
#define song_ingame_end      0x4AEA

/// Song 'song_ingame' array declaration
extern void song_ingame[song_ingame_size];
