// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _palette_H_
#define _palette_H_

#include <types.h>

extern const u8 palette[16];

#endif
